### ISSUE TITLE
Gulp error on fresh install

### ISSUE THREAD

**Issue by nigelwhite** [jorgetite/grav-theme-qboss#5]
$ cd user/themes/qbee // not a sub-theme
$ npm install
$ npm audit fix
$ gulp
`assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/qpc/docker-sites/ddev/projects/dhammapala/user/themes/qbee/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/qpc/docker-sites/ddev/projects/dhammapala/user/themes/qbee/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/qpc/docker-sites/ddev/projects/dhammapala/user/themes/qbee/gulpfile.js:19:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)`

Grav 1.5.10

**Comment by jorgetite** [comment]
To use the theme you just need to execute the following command from the root of your grave install:

`bin/gpm install qbee`

This will install the QBee theme into your /user/themes directory within Grav. The theme is ready to be used and there is no need to run npm or gulp.
